/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.base;

import com.aftership.http.AfterShipClient;
import com.aftership.AfterShip;

public abstract class Creator<T extends Resource> {

    public T create() throws Exception {
        return create(AfterShip.getRestClient());
    }

    public abstract T create(final AfterShipClient client) throws Exception;
}
