/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.base;

import com.aftership.AfterShip;
import com.aftership.http.AfterShipClient;

public abstract class Deleter<T extends Resource> {

  public T delete() throws Exception {
    return delete(AfterShip.getRestClient());
  }

  public abstract T delete(final AfterShipClient client) throws Exception;
}
