/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.base;

import java.util.List;

public class Page<T> {
    private int total;

    private int page;

    private int limit;

    private boolean hasNextPage;

    private List<T> records;

    public Page<T> setLimit(final int limit) {
        this.limit = limit;
        return this;
    }

    public List<T> getRecords() {
        return records;
    }

    public Page<T> setRecords(final List<T> records) {
        this.records = records;
        return this;
    }

    public int getTotal() {
        return total;
    }

    public Page<T> setTotal(final int total) {
        this.total = total;
        return this;
    }

    public int getPage() {
        return page;
    }

    public Page<T> setPage(final int page) {
        this.page = page;
        return this;
    }
}
