/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.base;

import java.util.List;

public class Page<T> {
    private int total;

    private boolean hasNextPage;

    private String nextCursor;

    private List<T> records;

    public Page<T> setHasNextCursor(boolean hasNextCursor) {
        this.hasNextPage = hasNextCursor;
        return this;
    }

    public Boolean getHasNextPage() {
        return hasNextPage;
    }

    public String getNextCursor() {
        return nextCursor;
    }

    public Page<T> setNextCursor(String nextCursor) {
        this.nextCursor = nextCursor;
        return this;
    }

    public List<T> getRecords() {
        return records;
    }

    public Page<T> setRecords(final List<T> records) {
        this.records = records;
        return this;
    }

    public int getTotal() {
        return total;
    }

    public Page<T> setTotal(final int total) {
        this.total = total;
        return this;
    }
}
