/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.base;

import com.aftership.AfterShip;
import com.aftership.http.AfterShipClient;

public abstract class Reader<T extends Resource> {

    public Page<T> read() throws Exception {
        return read(AfterShip.getRestClient());
    }

    public abstract Page<T> read(final AfterShipClient client) throws Exception;
}
