/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.model;

import com.google.gson.annotations.SerializedName;

public enum AdditionalFields {
  @SerializedName("tracking_account_number")
  TrackingAccountNumber("tracking_account_number"),

  @SerializedName("destination_postal_code")
  DestinationPostalCode("destination_postal_code"),

  @SerializedName("destination_state")
  DestinationState("destination_state"),

  @SerializedName("tracking_key")
  TrackingKey("tracking_key"),

  @SerializedName("origin_country_region")
  OriginCountryRegion("origin_country_region"),

  @SerializedName("destination_country_region")
  DestinationCountryRegion("destination_country_region"),

  @SerializedName("tracking_ship_date")
  TrackingShipDate("tracking_ship_date");

  private final String content;

  AdditionalFields(final String content) {
    this.content = content;
  }

  public String toString() {
    return content;
  }
}
