/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.base.Resource;

public class Courier extends Resource {

    @SerializedName("slug")
    private String slug;

    @SerializedName("name")
    private String name;

    @SerializedName("phone")
    private String phone;

    @SerializedName("other_name")
    private String otherName;

    @SerializedName("web_url")
    private String webUrl;

    @SerializedName("required_fields")
    private java.util.List<String> requiredFields;

    @SerializedName("optional_fields")
    private java.util.List<String> optionalFields;

    @SerializedName("default_language")
    private String defaultLanguage;

    @SerializedName("support_languages")
    private java.util.List<String> supportLanguages;

    @SerializedName("service_from_country_iso3")
    private java.util.List<String> serviceFromCountryIso3;

    public  String getSlug() {
        return slug;
    }

    public void setSlug( String slug) {
        this.slug = slug;
    }

    public  String getName() {
        return name;
    }

    public void setName( String name) {
        this.name = name;
    }

    public  String getPhone() {
        return phone;
    }

    public void setPhone( String phone) {
        this.phone = phone;
    }

    public  String getOtherName() {
        return otherName;
    }

    public void setOtherName( String otherName) {
        this.otherName = otherName;
    }

    public  String getWebUrl() {
        return webUrl;
    }

    public void setWebUrl( String webUrl) {
        this.webUrl = webUrl;
    }

    public java.util.List<String>  getRequiredFields() {
        return requiredFields;
    }

    public void setRequiredFields(java.util.List<String>  requiredFields) {
        this.requiredFields = requiredFields;
    }

    public java.util.List<String>  getOptionalFields() {
        return optionalFields;
    }

    public void setOptionalFields(java.util.List<String>  optionalFields) {
        this.optionalFields = optionalFields;
    }

    public  String getDefaultLanguage() {
        return defaultLanguage;
    }

    public void setDefaultLanguage( String defaultLanguage) {
        this.defaultLanguage = defaultLanguage;
    }

    public java.util.List<String>  getSupportLanguages() {
        return supportLanguages;
    }

    public void setSupportLanguages(java.util.List<String>  supportLanguages) {
        this.supportLanguages = supportLanguages;
    }

    public java.util.List<String>  getServiceFromCountryIso3() {
        return serviceFromCountryIso3;
    }

    public void setServiceFromCountryIso3(java.util.List<String>  serviceFromCountryIso3) {
        this.serviceFromCountryIso3 = serviceFromCountryIso3;
    }

}
