/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.model;

import com.aftership.base.Resource;
import com.google.gson.annotations.SerializedName;

public class CourierConnectionResponseForGetCourierConnections extends Resource {

  @SerializedName("meta")
  private Meta meta;

  @SerializedName("data")
  private DataCourierConnectionResponseForGetCourierConnections data;

  public Meta getMeta() {
    return meta;
  }

  public void setMeta(Meta meta) {
    this.meta = meta;
  }

  public DataCourierConnectionResponseForGetCourierConnections getData() {
    return data;
  }

  public void setData(DataCourierConnectionResponseForGetCourierConnections data) {
    this.data = data;
  }
}
