/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.model;

import com.aftership.base.Resource;
import com.google.gson.annotations.SerializedName;

public class CredentialsCourier extends Resource {

  @SerializedName("fields")
  private java.util.List<CredentialField> fields;

  public java.util.List<CredentialField> getFields() {
    return fields;
  }

  public void setFields(java.util.List<CredentialField> fields) {
    this.fields = fields;
  }
}
