/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.model;

import com.aftership.base.Resource;

public class CustomFieldsUpdateTrackingBySlugTrackingNumberRequest extends Resource {

}
