/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.model;

import com.aftership.base.Resource;
import com.google.gson.annotations.SerializedName;

public class DataCourierConnectionResponseForGetCourierConnections extends Resource {

  @SerializedName("pagination")
  private PaginationDataCourierConnectionResponseForGetCourierConnections pagination;

  @SerializedName("courier_connections")
  private java.util.List<CourierConnection> courierConnections;

  public PaginationDataCourierConnectionResponseForGetCourierConnections getPagination() {
    return pagination;
  }

  public void setPagination(
      PaginationDataCourierConnectionResponseForGetCourierConnections pagination) {
    this.pagination = pagination;
  }

  public java.util.List<CourierConnection> getCourierConnections() {
    return courierConnections;
  }

  public void setCourierConnections(java.util.List<CourierConnection> courierConnections) {
    this.courierConnections = courierConnections;
  }
}
