/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.base.Resource;

public class DataTrackingResponseGetMultipleV1 extends Resource {

    @SerializedName("page")
    private Integer page;

    @SerializedName("limit")
    private Integer limit;

    @SerializedName("count")
    private Integer count;

    @SerializedName("keyword")
    private String keyword;

    @SerializedName("slug")
    private String slug;

    @SerializedName("origin")
    private java.util.List<String> origin;

    @SerializedName("destination")
    private java.util.List<String> destination;

    @SerializedName("tag")
    private TagV1 tag;

    @SerializedName("created_at_min")
    private String createdAtMin;

    @SerializedName("created_at_max")
    private String createdAtMax;

    @SerializedName("last_updated_at")
    private String lastUpdatedAt;

    @SerializedName("return_to_sender")
    private java.util.List<Boolean> returnToSender;

    @SerializedName("courier_destination_country_iso3")
    private java.util.List<String> courierDestinationCountryIso3;

    @SerializedName("trackings")
    private java.util.List<Tracking> trackings;

    public  Integer getPage() {
        return page;
    }

    public void setPage( Integer page) {
        this.page = page;
    }

    public  Integer getLimit() {
        return limit;
    }

    public void setLimit( Integer limit) {
        this.limit = limit;
    }

    public  Integer getCount() {
        return count;
    }

    public void setCount( Integer count) {
        this.count = count;
    }

    public  String getKeyword() {
        return keyword;
    }

    public void setKeyword( String keyword) {
        this.keyword = keyword;
    }

    public  String getSlug() {
        return slug;
    }

    public void setSlug( String slug) {
        this.slug = slug;
    }

    public java.util.List<String>  getOrigin() {
        return origin;
    }

    public void setOrigin(java.util.List<String>  origin) {
        this.origin = origin;
    }

    public java.util.List<String>  getDestination() {
        return destination;
    }

    public void setDestination(java.util.List<String>  destination) {
        this.destination = destination;
    }

    public  TagV1 getTag() {
        return tag;
    }

    public void setTag( TagV1 tag) {
        this.tag = tag;
    }

    public  String getCreatedAtMin() {
        return createdAtMin;
    }

    public void setCreatedAtMin( String createdAtMin) {
        this.createdAtMin = createdAtMin;
    }

    public  String getCreatedAtMax() {
        return createdAtMax;
    }

    public void setCreatedAtMax( String createdAtMax) {
        this.createdAtMax = createdAtMax;
    }

    public  String getLastUpdatedAt() {
        return lastUpdatedAt;
    }

    public void setLastUpdatedAt( String lastUpdatedAt) {
        this.lastUpdatedAt = lastUpdatedAt;
    }

    public java.util.List<Boolean>  getReturnToSender() {
        return returnToSender;
    }

    public void setReturnToSender(java.util.List<Boolean>  returnToSender) {
        this.returnToSender = returnToSender;
    }

    public java.util.List<String>  getCourierDestinationCountryIso3() {
        return courierDestinationCountryIso3;
    }

    public void setCourierDestinationCountryIso3(java.util.List<String>  courierDestinationCountryIso3) {
        this.courierDestinationCountryIso3 = courierDestinationCountryIso3;
    }

    public java.util.List<Tracking>  getTrackings() {
        return trackings;
    }

    public void setTrackings(java.util.List<Tracking>  trackings) {
        this.trackings = trackings;
    }

}
