/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.model;

import com.aftership.base.Resource;
import com.google.gson.annotations.SerializedName;

public class DeleteCourierConnectionsByIdResponse extends Resource {

  @SerializedName("id")
  private String id;

  @SerializedName("courier_slug")
  private String courierSlug;

  @SerializedName("credentials")
  private java.util.Map<String, String> credentials;

  @SerializedName("created_at")
  private String createdAt;

  @SerializedName("updated_at")
  private String updatedAt;

  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public String getCourierSlug() {
    return courierSlug;
  }

  public void setCourierSlug(String courierSlug) {
    this.courierSlug = courierSlug;
  }

  public java.util.Map<String, String> getCredentials() {
    return credentials;
  }

  public void setCredentials(java.util.Map<String, String> credentials) {
    this.credentials = credentials;
  }

  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  public String getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }
}
