/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.model;

import com.aftership.base.Resource;
import com.google.gson.annotations.SerializedName;

public class DetectCourierRequest extends Resource {

  @SerializedName("tracking_number")
  private String trackingNumber;

  @SerializedName("slug")
  private java.util.List<String> slug;

  @SerializedName("tracking_postal_code")
  private String trackingPostalCode;

  @SerializedName("tracking_ship_date")
  private String trackingShipDate;

  @SerializedName("tracking_account_number")
  private String trackingAccountNumber;

  @SerializedName("tracking_key")
  private String trackingKey;

  @SerializedName("tracking_origin_country_region")
  private String trackingOriginCountryRegion;

  @SerializedName("tracking_destination_country_region")
  private String trackingDestinationCountryRegion;

  @SerializedName("tracking_state")
  private String trackingState;

  @SerializedName("slug_group")
  private SlugGroupV1 slugGroup;

  @SerializedName("origin_country_region")
  private String originCountryRegion;

  @SerializedName("destination_country_region")
  private String destinationCountryRegion;

  public String getTrackingNumber() {
    return trackingNumber;
  }

  public void setTrackingNumber(String trackingNumber) {
    this.trackingNumber = trackingNumber;
  }

  public java.util.List<String> getSlug() {
    return slug;
  }

  public void setSlug(java.util.List<String> slug) {
    this.slug = slug;
  }

  public String getTrackingPostalCode() {
    return trackingPostalCode;
  }

  public void setTrackingPostalCode(String trackingPostalCode) {
    this.trackingPostalCode = trackingPostalCode;
  }

  public String getTrackingShipDate() {
    return trackingShipDate;
  }

  public void setTrackingShipDate(String trackingShipDate) {
    this.trackingShipDate = trackingShipDate;
  }

  public String getTrackingAccountNumber() {
    return trackingAccountNumber;
  }

  public void setTrackingAccountNumber(String trackingAccountNumber) {
    this.trackingAccountNumber = trackingAccountNumber;
  }

  public String getTrackingKey() {
    return trackingKey;
  }

  public void setTrackingKey(String trackingKey) {
    this.trackingKey = trackingKey;
  }

  public String getTrackingOriginCountryRegion() {
    return trackingOriginCountryRegion;
  }

  public void setTrackingOriginCountryRegion(String trackingOriginCountryRegion) {
    this.trackingOriginCountryRegion = trackingOriginCountryRegion;
  }

  public String getTrackingDestinationCountryRegion() {
    return trackingDestinationCountryRegion;
  }

  public void setTrackingDestinationCountryRegion(String trackingDestinationCountryRegion) {
    this.trackingDestinationCountryRegion = trackingDestinationCountryRegion;
  }

  public String getTrackingState() {
    return trackingState;
  }

  public void setTrackingState(String trackingState) {
    this.trackingState = trackingState;
  }

  public SlugGroupV1 getSlugGroup() {
    return slugGroup;
  }

  public void setSlugGroup(SlugGroupV1 slugGroup) {
    this.slugGroup = slugGroup;
  }

  public String getOriginCountryRegion() {
    return originCountryRegion;
  }

  public void setOriginCountryRegion(String originCountryRegion) {
    this.originCountryRegion = originCountryRegion;
  }

  public String getDestinationCountryRegion() {
    return destinationCountryRegion;
  }

  public void setDestinationCountryRegion(String destinationCountryRegion) {
    this.destinationCountryRegion = destinationCountryRegion;
  }
}
