/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.model;

import com.aftership.base.Resource;
import com.google.gson.annotations.SerializedName;

public class EstimatedPickupPredictRequest extends Resource {

  @SerializedName("order_time")
  private String orderTime;

  @SerializedName("order_cutoff_time")
  private String orderCutoffTime;

  @SerializedName("business_days")
  private java.util.List<Integer> businessDays;

  @SerializedName("order_processing_time")
  private OrderProcessingTimeEstimatedPickupPredictRequest orderProcessingTime;

  public String getOrderTime() {
    return orderTime;
  }

  public void setOrderTime(String orderTime) {
    this.orderTime = orderTime;
  }

  public String getOrderCutoffTime() {
    return orderCutoffTime;
  }

  public void setOrderCutoffTime(String orderCutoffTime) {
    this.orderCutoffTime = orderCutoffTime;
  }

  public java.util.List<Integer> getBusinessDays() {
    return businessDays;
  }

  public void setBusinessDays(java.util.List<Integer> businessDays) {
    this.businessDays = businessDays;
  }

  public OrderProcessingTimeEstimatedPickupPredictRequest getOrderProcessingTime() {
    return orderProcessingTime;
  }

  public void setOrderProcessingTime(
      OrderProcessingTimeEstimatedPickupPredictRequest orderProcessingTime) {
    this.orderProcessingTime = orderProcessingTime;
  }
}
