/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.model;

import com.aftership.base.Resource;
import com.google.gson.annotations.SerializedName;

public class FirstMileTracking extends Resource {

  @SerializedName("tracking_number")
  private String trackingNumber;

  @SerializedName("slug")
  private String slug;

  @SerializedName("transit_time")
  private String transitTime;

  @SerializedName("courier_redirect_link")
  private String courierRedirectLink;

  @SerializedName("courier_tracking_link")
  private String courierTrackingLink;

  public String getTrackingNumber() {
    return trackingNumber;
  }

  public void setTrackingNumber(String trackingNumber) {
    this.trackingNumber = trackingNumber;
  }

  public String getSlug() {
    return slug;
  }

  public void setSlug(String slug) {
    this.slug = slug;
  }

  public String getTransitTime() {
    return transitTime;
  }

  public void setTransitTime(String transitTime) {
    this.transitTime = transitTime;
  }

  public String getCourierRedirectLink() {
    return courierRedirectLink;
  }

  public void setCourierRedirectLink(String courierRedirectLink) {
    this.courierRedirectLink = courierRedirectLink;
  }

  public String getCourierTrackingLink() {
    return courierTrackingLink;
  }

  public void setCourierTrackingLink(String courierTrackingLink) {
    this.courierTrackingLink = courierTrackingLink;
  }
}
