/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.base.Resource;

public class GetNotificationBySlugTrackingNumberResponse extends Resource {

    @SerializedName("notification")
    private Notification notification;

    public  Notification getNotification() {
        return notification;
    }

    public void setNotification( Notification notification) {
        this.notification = notification;
    }

}
