/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.model;

import com.aftership.base.Resource;
import com.google.gson.annotations.SerializedName;

public class GetTrackingsResponse extends Resource {

    @SerializedName("pagination")
    private PaginationGetTrackingsResponse pagination;

    @SerializedName("trackings")
    private java.util.List<Tracking> trackings;

    public PaginationGetTrackingsResponse getPagination() {
        return pagination;
    }

    public void setPagination(PaginationGetTrackingsResponse pagination) {
        this.pagination = pagination;
    }

    public java.util.List<Tracking> getTrackings() {
        return trackings;
    }

    public void setTrackings(java.util.List<Tracking> trackings) {
        this.trackings = trackings;
    }

}
