/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.base.Resource;

public class MarkTrackingCompletedByIdRequest extends Resource {

    @SerializedName("reason")
    private String reason;

    public  String getReason() {
        return reason;
    }

    public void setReason( String reason) {
        this.reason = reason;
    }

}
