/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.base.Resource;

public class NotificationRequestV1 extends Resource {

    @SerializedName("emails")
    private java.util.List<String> emails;

    @SerializedName("smses")
    private java.util.List<String> smses;

    public java.util.List<String>  getEmails() {
        return emails;
    }

    public void setEmails(java.util.List<String>  emails) {
        this.emails = emails;
    }

    public java.util.List<String>  getSmses() {
        return smses;
    }

    public void setSmses(java.util.List<String>  smses) {
        this.smses = smses;
    }

}
