/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.base.Resource;

public class PartialDeleteTracking extends Resource {

    @SerializedName("id")
    private String id;

    @SerializedName("tracking_number")
    private String trackingNumber;

    @SerializedName("slug")
    private String slug;

    @SerializedName("tracking_account_number")
    private String trackingAccountNumber;

    @SerializedName("tracking_key")
    private String trackingKey;

    @SerializedName("tracking_ship_date")
    private String trackingShipDate;

    @SerializedName("tracking_origin_country")
    private String trackingOriginCountry;

    @SerializedName("tracking_destination_country")
    private String trackingDestinationCountry;

    @SerializedName("tracking_postal_code")
    private String trackingPostalCode;

    @SerializedName("tracking_state")
    private String trackingState;

    public  String getId() {
        return id;
    }

    public void setId( String id) {
        this.id = id;
    }

    public  String getTrackingNumber() {
        return trackingNumber;
    }

    public void setTrackingNumber( String trackingNumber) {
        this.trackingNumber = trackingNumber;
    }

    public  String getSlug() {
        return slug;
    }

    public void setSlug( String slug) {
        this.slug = slug;
    }

    public  String getTrackingAccountNumber() {
        return trackingAccountNumber;
    }

    public void setTrackingAccountNumber( String trackingAccountNumber) {
        this.trackingAccountNumber = trackingAccountNumber;
    }

    public  String getTrackingKey() {
        return trackingKey;
    }

    public void setTrackingKey( String trackingKey) {
        this.trackingKey = trackingKey;
    }

    public  String getTrackingShipDate() {
        return trackingShipDate;
    }

    public void setTrackingShipDate( String trackingShipDate) {
        this.trackingShipDate = trackingShipDate;
    }

    public  String getTrackingOriginCountry() {
        return trackingOriginCountry;
    }

    public void setTrackingOriginCountry( String trackingOriginCountry) {
        this.trackingOriginCountry = trackingOriginCountry;
    }

    public  String getTrackingDestinationCountry() {
        return trackingDestinationCountry;
    }

    public void setTrackingDestinationCountry( String trackingDestinationCountry) {
        this.trackingDestinationCountry = trackingDestinationCountry;
    }

    public  String getTrackingPostalCode() {
        return trackingPostalCode;
    }

    public void setTrackingPostalCode( String trackingPostalCode) {
        this.trackingPostalCode = trackingPostalCode;
    }

    public  String getTrackingState() {
        return trackingState;
    }

    public void setTrackingState( String trackingState) {
        this.trackingState = trackingState;
    }

}
