/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.model;

import com.aftership.base.Resource;
import com.google.gson.annotations.SerializedName;

public class PostCourierConnectionsRequest extends Resource {

  @SerializedName("courier_slug")
  private String courierSlug;

  @SerializedName("credentials")
  private java.util.Map<String, String> credentials;

  public String getCourierSlug() {
    return courierSlug;
  }

  public void setCourierSlug(String courierSlug) {
    this.courierSlug = courierSlug;
  }

  public java.util.Map<String, String> getCredentials() {
    return credentials;
  }

  public void setCredentials(java.util.Map<String, String> credentials) {
    this.credentials = credentials;
  }
}
