/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.model;

import com.aftership.base.Resource;
import com.google.gson.annotations.SerializedName;

public class PutCourierConnectionsByIdRequest extends Resource {

  @SerializedName("credentials")
  private java.util.Map<String, String> credentials;

  public java.util.Map<String, String> getCredentials() {
    return credentials;
  }

  public void setCredentials(java.util.Map<String, String> credentials) {
    this.credentials = credentials;
  }
}
