/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.base.Resource;

public class RetrackTrackingByIdResponse extends Resource {

    @SerializedName("tracking")
    private PartialUpdateTracking tracking;

    public  PartialUpdateTracking getTracking() {
        return tracking;
    }

    public void setTracking( PartialUpdateTracking tracking) {
        this.tracking = tracking;
    }

}
