/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.base.Resource;

public class UpdateTrackingByIdResponse extends Resource {

    @SerializedName("tracking")
    private Tracking tracking;

    public  Tracking getTracking() {
        return tracking;
    }

    public void setTracking( Tracking tracking) {
        this.tracking = tracking;
    }

}
