/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.base.Resource;

public class UpdateTrackingByIdRequest extends Resource {

    @SerializedName("tracking")
    private TrackingUpdateTrackingByIdRequest tracking;

    public  TrackingUpdateTrackingByIdRequest getTracking() {
        return tracking;
    }

    public void setTracking( TrackingUpdateTrackingByIdRequest tracking) {
        this.tracking = tracking;
    }

}
