/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.base.Resource;

public class UpdateTrackingBySlugTrackingNumberRequest extends Resource {

    @SerializedName("tracking")
    private TrackingUpdateTrackingBySlugTrackingNumberRequest tracking;

    public  TrackingUpdateTrackingBySlugTrackingNumberRequest getTracking() {
        return tracking;
    }

    public void setTracking( TrackingUpdateTrackingBySlugTrackingNumberRequest tracking) {
        this.tracking = tracking;
    }

}
