/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.courier_connection;

import com.aftership.base.Resource;

public class CourierConnectionResource extends Resource {
  public static GetCourierConnectionsByIdFetcher getCourierConnectionsById() {
    return new GetCourierConnectionsByIdFetcher();
  }

  public static GetCourierConnectionsReader getCourierConnections() {
    return new GetCourierConnectionsReader();
  }

  public static PutCourierConnectionsByIdUpdater putCourierConnectionsById() {
    return new PutCourierConnectionsByIdUpdater();
  }

  public static DeleteCourierConnectionsByIdDeleter deleteCourierConnectionsById() {
    return new DeleteCourierConnectionsByIdDeleter();
  }

  public static PostCourierConnectionsCreator postCourierConnections() {
    return new PostCourierConnectionsCreator();
  }
}
