/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.courier_connection;

import com.aftership.base.Deleter;
import com.aftership.constant.ErrorEnum;
import com.aftership.exception.ApiException;
import com.aftership.http.*;
import com.aftership.http.Request;
import com.aftership.model.CourierConnection;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.util.HashMap;
import java.util.Map;

public class DeleteCourierConnectionsByIdDeleter extends Deleter<CourierConnection> {
  private final Map<String, String> headerParams = new HashMap<>(8);

  public DeleteCourierConnectionsByIdDeleter addHeaderParam(final String name, final String value) {
    if (value == null || value.equals("null")) {
      return this;
    }

    if (!headerParams.containsKey(name)) {
      headerParams.put(name, value);
    }
    return this;
  }

  private void setHeaderParams(final Request request) {
    for (final Map.Entry<String, String> entry : headerParams.entrySet()) {
      request.addHeaderParam(entry.getKey(), entry.getValue());
    }
  }

  private String id;

  public DeleteCourierConnectionsByIdDeleter setId(String id) {
    this.id = id;
    return this;
  }

  @Override
  public CourierConnection delete(AfterShipClient client) throws Exception {
    if (id == null || id.isEmpty()) {
      throw new ApiException(
          ErrorEnum.BAD_REQUEST.getCode(),
          ErrorEnum.BAD_REQUEST.getMessage() + ": `id` is invalid");
    }
    String path = String.format("/tracking/2025-07/courier-connections/%s", id);
    Request request = new Request(HttpMethod.DELETE, path);
    setHeaderParams(request);
    Response response = client.request(request);
    AfterShipResponse<CourierConnection> trackingResponse =
        new Gson()
            .fromJson(
                response.getContent(),
                new TypeToken<AfterShipResponse<CourierConnection>>() {}.getType());
    return trackingResponse.getData();
  }
}
