/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.courier_connection;

import com.aftership.base.Page;
import com.aftership.base.Reader;
import com.aftership.http.*;
import com.aftership.http.Request;
import com.aftership.model.CourierConnection;
import com.aftership.model.GetCourierConnectionsResponse;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.util.HashMap;
import java.util.Map;

public class GetCourierConnectionsReader extends Reader<CourierConnection> {
  private final Map<String, String> headerParams = new HashMap<>(8);

  public GetCourierConnectionsReader addHeaderParam(final String name, final String value) {
    if (value == null || value.equals("null")) {
      return this;
    }

    if (!headerParams.containsKey(name)) {
      headerParams.put(name, value);
    }
    return this;
  }

  private void setHeaderParams(final Request request) {
    for (final Map.Entry<String, String> entry : headerParams.entrySet()) {
      request.addHeaderParam(entry.getKey(), entry.getValue());
    }
  }

  private String courierSlug;

  private String cursor;

  private String limit;

  public GetCourierConnectionsReader setCourierSlug(String courierSlug) {
    this.courierSlug = courierSlug;
    return this;
  }

  public GetCourierConnectionsReader setCursor(String cursor) {
    this.cursor = cursor;
    return this;
  }

  public GetCourierConnectionsReader setLimit(String limit) {
    this.limit = limit;
    return this;
  }

  @Override
  public Page<CourierConnection> read(AfterShipClient client) throws Exception {
    String path = "/tracking/2025-04/courier-connections";
    Request request = new Request(HttpMethod.GET, path);
    addQueryParams(request);
    setHeaderParams(request);
    Response response = client.request(request);
    AfterShipResponse<GetCourierConnectionsResponse> trackingResponse =
        new Gson()
            .fromJson(
                response.getContent(),
                new TypeToken<AfterShipResponse<GetCourierConnectionsResponse>>() {}.getType());
    Page<CourierConnection> pageResponse = new Page<>();
    pageResponse
        .setNextCursor(trackingResponse.getData().getPagination().getNextCursor())
        .setHasNextCursor(trackingResponse.getData().getPagination().getHasNextPage())
        .setTotal(trackingResponse.getData().getPagination().getTotal())
        .setRecords(trackingResponse.getData().getCourierConnections());

    return pageResponse;
  }

  private void addQueryParams(final Request request) {
    if (courierSlug != null) {
      request.addQueryParam("courier_slug", courierSlug);
    }
    if (cursor != null) {
      request.addQueryParam("cursor", cursor);
    }
    if (limit != null) {
      request.addQueryParam("limit", limit);
    }
  }
}
