/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.courier_connection;

import com.aftership.base.Creator;
import com.aftership.http.*;
import com.aftership.http.Request;
import com.aftership.model.CourierConnection;
import com.aftership.model.PostCourierConnectionsRequest;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.util.HashMap;
import java.util.Map;

public class PostCourierConnectionsCreator extends Creator<CourierConnection> {
  private final Map<String, String> headerParams = new HashMap<>(8);

  public PostCourierConnectionsCreator addHeaderParam(final String name, final String value) {
    if (value == null || value.equals("null")) {
      return this;
    }

    if (!headerParams.containsKey(name)) {
      headerParams.put(name, value);
    }
    return this;
  }

  private void setHeaderParams(final Request request) {
    for (final Map.Entry<String, String> entry : headerParams.entrySet()) {
      request.addHeaderParam(entry.getKey(), entry.getValue());
    }
  }

  private PostCourierConnectionsRequest postCourierConnectionsRequest;

  public PostCourierConnectionsCreator setPostCourierConnectionsRequest(
      PostCourierConnectionsRequest postCourierConnectionsRequest) {
    this.postCourierConnectionsRequest = postCourierConnectionsRequest;
    return this;
  }

  @Override
  public CourierConnection create(AfterShipClient client) throws Exception {
    String path = "/tracking/2025-04/courier-connections";
    Request request = new Request(HttpMethod.POST, path);
    request.setBody((new Gson()).toJson(postCourierConnectionsRequest));

    setHeaderParams(request);
    Response response = client.request(request);
    AfterShipResponse<CourierConnection> trackingResponse =
        new Gson()
            .fromJson(
                response.getContent(),
                new TypeToken<AfterShipResponse<CourierConnection>>() {}.getType());
    return trackingResponse.getData();
  }
}
