/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.estimated_delivery_date;

import com.aftership.base.Resource;

public class EstimatedDeliveryDateResource extends Resource {
    public static PredictBatchCreator predictBatch() {
        return new PredictBatchCreator();
    }
}
