/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.estimated_delivery_date;

import com.aftership.base.Creator;
import com.aftership.http.*;
import com.aftership.model.EstimatedDeliveryDateRequest;
import com.aftership.model.EstimatedDeliveryDateResponse;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.util.HashMap;
import java.util.Map;

public class PredictCreator extends Creator<EstimatedDeliveryDateResponse> {
  private final Map<String, String> headerParams = new HashMap<>(8);
  private EstimatedDeliveryDateRequest predictRequest;

  public PredictCreator addHeaderParam(final String name, final String value) {
    if (value == null || value.equals("null")) {
      return this;
    }

    if (!headerParams.containsKey(name)) {
      headerParams.put(name, value);
    }
    return this;
  }

  private void setHeaderParams(final Request request) {
    for (final Map.Entry<String, String> entry : headerParams.entrySet()) {
      request.addHeaderParam(entry.getKey(), entry.getValue());
    }
  }

  public PredictCreator setEstimatedDeliveryDateRequest(
      EstimatedDeliveryDateRequest predictRequest) {
    this.predictRequest = predictRequest;
    return this;
  }

  @Override
  public EstimatedDeliveryDateResponse create(AfterShipClient client) throws Exception {
    String path = "/tracking/2025-01/estimated-delivery-date/predict";
    Request request = new Request(HttpMethod.POST, path);
    request.setBody((new Gson()).toJson(predictRequest));

    setHeaderParams(request);
    Response response = client.request(request);
    AfterShipResponse<EstimatedDeliveryDateResponse> trackingResponse =
        new Gson()
            .fromJson(
                response.getContent(),
                new TypeToken<AfterShipResponse<EstimatedDeliveryDateResponse>>() {}.getType());
    return trackingResponse.getData();
  }
}
