/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.tracking.courier_connection;

import com.aftership.tracking.base.Resource;

public class CourierConnectionResource extends Resource {
  public static GetCourierConnectionsFetcher getCourierConnections() {
    return new GetCourierConnectionsFetcher();
  }

  public static PostCourierConnectionsCreator postCourierConnections() {
    return new PostCourierConnectionsCreator();
  }

  public static GetCourierConnectionsByIdFetcher getCourierConnectionsById() {
    return new GetCourierConnectionsByIdFetcher();
  }

  public static PutCourierConnectionsByIdUpdater putCourierConnectionsById() {
    return new PutCourierConnectionsByIdUpdater();
  }

  public static DeleteCourierConnectionsByIdDeleter deleteCourierConnectionsById() {
    return new DeleteCourierConnectionsByIdDeleter();
  }
}
