/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.tracking.courier_connection;

import com.aftership.tracking.base.Fetcher;
import com.aftership.tracking.constant.ErrorEnum;
import com.aftership.tracking.exception.ApiException;
import com.aftership.tracking.http.*;
import com.aftership.tracking.http.Request;
import com.aftership.tracking.model.CourierConnection;
import com.aftership.tracking.model.GetCourierConnectionsByIdResponse;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.util.HashMap;
import java.util.Map;

public class GetCourierConnectionsByIdFetcher extends Fetcher<GetCourierConnectionsByIdResponse> {
  private final Map<String, String> headerParams = new HashMap<>(8);

  public GetCourierConnectionsByIdFetcher addHeaderParam(final String name, final String value) {
    if (value == null || value.equals("null")) {
      return this;
    }

    if (!headerParams.containsKey(name)) {
      headerParams.put(name, value);
    }
    return this;
  }

  private void setHeaderParams(final Request request) {
    for (final Map.Entry<String, String> entry : headerParams.entrySet()) {
      request.addHeaderParam(entry.getKey(), entry.getValue());
    }
  }

  private String id;

  public GetCourierConnectionsByIdFetcher setId(String id) {
    this.id = id;
    return this;
  }

  @Override
  public GetCourierConnectionsByIdResponse fetch(AfterShipClient client) throws Exception {
    if (id == null || id.isEmpty()) {
      throw new ApiException(ErrorEnum.BAD_REQUEST.name(), "Invalid request: `id` is invalid");
    }
    String path = String.format("/tracking/2026-07/courier-connections/%s", id);
    Request request = new Request(HttpMethod.GET, path);
    setHeaderParams(request);
    Response response = client.request(request);
    AfterShipResponse<CourierConnection> responseData =
        new Gson()
            .fromJson(
                response.getContent(),
                new TypeToken<AfterShipResponse<CourierConnection>>() {}.getType());
    GetCourierConnectionsByIdResponse result = new GetCourierConnectionsByIdResponse();
    result.setData(responseData.getData());
    result.setResponseHeader(response.getResponseHeader());
    return result;
  }
}
