/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.http;

public class Response {
    private final int statusCode;
    private final String content;
    private final boolean isTimeout;

    public Response() {
        this.statusCode = 0;
        this.content = "";
        this.isTimeout = true;
    }

    public Response(String content, int statusCode, boolean isTimeout) {
        this.content = content;
        this.statusCode = statusCode;
        this.isTimeout = isTimeout;
    }

    public String getContent() {
        return content;
    }

    public int getStatusCode() {
        return statusCode;
    }

    public boolean isTimeout() {
        return isTimeout;
    }
}
