/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.tracking.estimated_delivery_date;

import com.aftership.tracking.base.Creator;
import com.aftership.tracking.constant.ErrorEnum;
import com.aftership.tracking.exception.ApiException;
import com.aftership.tracking.http.*;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.util.HashMap;
import java.util.Map;
import com.aftership.tracking.http.Request;
import com.aftership.tracking.model.PredictResponse;
import com.aftership.tracking.model.EstimatedDeliveryDateResponse;
import com.aftership.tracking.model.EstimatedDeliveryDateRequest;

public class PredictCreator extends Creator<PredictResponse> {
    private final Map<String, String> headerParams= new HashMap<>(8);

    public PredictCreator addHeaderParam(final String name, final String value) {
        if (value == null || value.equals("null")) {
            return this;
        }

        if (!headerParams.containsKey(name)) {
            headerParams.put(name, value);
        }
        return this;
    }

    private void setHeaderParams(final Request request) {
        for (final Map.Entry<String, String> entry : headerParams.entrySet()) {
            request.addHeaderParam(entry.getKey(), entry.getValue());
        }
    }
    private EstimatedDeliveryDateRequest predictRequest;

    public PredictCreator setPredictRequest(EstimatedDeliveryDateRequest predictRequest) {
        this.predictRequest = predictRequest;
        return this;
    }

    @Override
    public PredictResponse create(AfterShipClient client) throws Exception {
        String path = "/tracking/2026-01/estimated-delivery-date/predict";
        Request request = new Request(HttpMethod.POST, path);
        request.setBody((new Gson()).toJson(predictRequest));

        setHeaderParams(request);
        Response response = client.request(request);
        AfterShipResponse<EstimatedDeliveryDateResponse> responseData = new Gson().fromJson(response.getContent(), new TypeToken<AfterShipResponse<EstimatedDeliveryDateResponse>>() {
            }.getType());
        PredictResponse result = new PredictResponse();
        result.setData(responseData.getData());
        result.setResponseHeader(response.getResponseHeader());
        return result;
    }

}
