/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.tracking;

import com.aftership.base.Creator;
import com.aftership.constant.ErrorEnum;
import com.aftership.exception.ApiException;
import com.aftership.http.*;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.util.HashMap;
import java.util.Map;
import com.aftership.http.Request;
import com.aftership.model.CreateTrackingResponse;
import com.aftership.base.Page;
import com.aftership.model.CreateTrackingRequest;
import com.aftership.model.Tracking;
import com.aftership.model.TrackingCreateTrackingRequest;

import com.aftership.model.CreateTrackingResponse;

public class CreateTrackingCreator extends Creator<Tracking> {
    private final Map<String, String> headerParams= new HashMap<>(8);

    public CreateTrackingCreator addHeaderParam(final String name, final String value) {
        if (value == null || value.equals("null")) {
            return this;
        }

        if (!headerParams.containsKey(name)) {
            headerParams.put(name, value);
        }
        return this;
    }

    private void setHeaderParams(final Request request) {
        for (final Map.Entry<String, String> entry : headerParams.entrySet()) {
            request.addHeaderParam(entry.getKey(), entry.getValue());
        }
    }
    private TrackingCreateTrackingRequest createTrackingRequest;

    public CreateTrackingCreator setTrackingCreateTrackingRequest(TrackingCreateTrackingRequest createTrackingRequest) {
        this.createTrackingRequest = createTrackingRequest;
        return this;
    }

    @Override
    public Tracking create(AfterShipClient client) throws Exception {
        String path = "/tracking/2024-04/trackings";
        Request request = new Request(HttpMethod.POST, path);
        CreateTrackingRequest TrackingCreateTrackingRequest = new CreateTrackingRequest();
        TrackingCreateTrackingRequest.setTracking(createTrackingRequest);
        request.setBody((new Gson()).toJson(TrackingCreateTrackingRequest));

        setHeaderParams(request);
        Response response = client.request(request);
        AfterShipResponse<CreateTrackingResponse> trackingResponse = new Gson().fromJson(response.getContent(), new TypeToken<AfterShipResponse<CreateTrackingResponse>>() {
            }.getType());
        return trackingResponse.getData().getTracking();

    }

}
