/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.tracking;

import com.aftership.base.Fetcher;
import com.aftership.constant.ErrorEnum;
import com.aftership.exception.ApiException;
import com.aftership.http.*;
import com.aftership.model.Tracking;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.util.HashMap;
import java.util.Map;

public class GetTrackingByIdFetcher extends Fetcher<Tracking> {
  private final Map<String, String> headerParams = new HashMap<>(8);
  private String fields;
  private String lang;
  private String id;

  public GetTrackingByIdFetcher addHeaderParam(final String name, final String value) {
    if (value == null || value.equals("null")) {
      return this;
    }

    if (!headerParams.containsKey(name)) {
      headerParams.put(name, value);
    }
    return this;
  }

  private void setHeaderParams(final Request request) {
    for (final Map.Entry<String, String> entry : headerParams.entrySet()) {
      request.addHeaderParam(entry.getKey(), entry.getValue());
    }
  }

  public GetTrackingByIdFetcher setFields(String fields) {
    this.fields = fields;
    return this;
  }

  public GetTrackingByIdFetcher setLang(String lang) {
    this.lang = lang;
    return this;
  }

  public GetTrackingByIdFetcher setId(String id) {
    this.id = id;
    return this;
  }

  @Override
  public Tracking fetch(AfterShipClient client) throws Exception {
    if (id == null || id.isEmpty()) {
      throw new ApiException(
          ErrorEnum.BAD_REQUEST.getCode(),
          ErrorEnum.BAD_REQUEST.getMessage() + ": `id` is invalid");
    }
    String path = String.format("/tracking/2025-01/trackings/%s", id);
    Request request = new Request(HttpMethod.GET, path);
    addQueryParams(request);
    setHeaderParams(request);
    Response response = client.request(request);
    AfterShipResponse<Tracking> trackingResponse =
        new Gson()
            .fromJson(
                response.getContent(), new TypeToken<AfterShipResponse<Tracking>>() {}.getType());
    return trackingResponse.getData();
  }

  private void addQueryParams(final Request request) {
    if (fields != null) {
      request.addQueryParam("fields", fields);
    }
    if (lang != null) {
      request.addQueryParam("lang", lang);
    }
  }
}
