/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.tracking.tracking;

import com.aftership.tracking.base.Creator;
import com.aftership.tracking.constant.ErrorEnum;
import com.aftership.tracking.exception.ApiException;
import com.aftership.tracking.http.*;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.util.HashMap;
import java.util.Map;
import com.aftership.tracking.http.Request;
import com.aftership.tracking.model.CreateTrackingResponse;
import com.aftership.tracking.model.Tracking;
import com.aftership.tracking.model.CreateTrackingRequest;

public class CreateTrackingCreator extends Creator<CreateTrackingResponse> {
    private final Map<String, String> headerParams= new HashMap<>(8);

    public CreateTrackingCreator addHeaderParam(final String name, final String value) {
        if (value == null || value.equals("null")) {
            return this;
        }

        if (!headerParams.containsKey(name)) {
            headerParams.put(name, value);
        }
        return this;
    }

    private void setHeaderParams(final Request request) {
        for (final Map.Entry<String, String> entry : headerParams.entrySet()) {
            request.addHeaderParam(entry.getKey(), entry.getValue());
        }
    }
    private CreateTrackingRequest createTrackingRequest;

    public CreateTrackingCreator setCreateTrackingRequest(CreateTrackingRequest createTrackingRequest) {
        this.createTrackingRequest = createTrackingRequest;
        return this;
    }

    @Override
    public CreateTrackingResponse create(AfterShipClient client) throws Exception {
        String path = "/tracking/2025-07/trackings";
        Request request = new Request(HttpMethod.POST, path);
        request.setBody((new Gson()).toJson(createTrackingRequest));

        setHeaderParams(request);
        Response response = client.request(request);
        AfterShipResponse<Tracking> responseData = new Gson().fromJson(response.getContent(), new TypeToken<AfterShipResponse<Tracking>>() {
            }.getType());
        CreateTrackingResponse result = new CreateTrackingResponse();
        result.setData(responseData.getData());
        result.setResponseHeader(response.getResponseHeader());
        return result;
    }

}
