/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.tracking.tracking;

import com.aftership.tracking.base.Creator;
import com.aftership.tracking.constant.ErrorEnum;
import com.aftership.tracking.exception.ApiException;
import com.aftership.tracking.http.*;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.util.HashMap;
import java.util.Map;
import com.aftership.tracking.http.Request;
import com.aftership.tracking.model.MarkTrackingCompletedByIdResponse;
import com.aftership.tracking.model.Tracking;
import com.aftership.tracking.model.MarkTrackingCompletedByIdRequest;

public class MarkTrackingCompletedByIdCreator extends Creator<MarkTrackingCompletedByIdResponse> {
    private final Map<String, String> headerParams= new HashMap<>(8);

    public MarkTrackingCompletedByIdCreator addHeaderParam(final String name, final String value) {
        if (value == null || value.equals("null")) {
            return this;
        }

        if (!headerParams.containsKey(name)) {
            headerParams.put(name, value);
        }
        return this;
    }

    private void setHeaderParams(final Request request) {
        for (final Map.Entry<String, String> entry : headerParams.entrySet()) {
            request.addHeaderParam(entry.getKey(), entry.getValue());
        }
    }
    private MarkTrackingCompletedByIdRequest markTrackingCompletedByIdRequest;

    public MarkTrackingCompletedByIdCreator setMarkTrackingCompletedByIdRequest(MarkTrackingCompletedByIdRequest markTrackingCompletedByIdRequest) {
        this.markTrackingCompletedByIdRequest = markTrackingCompletedByIdRequest;
        return this;
    }
    private String id;


    public MarkTrackingCompletedByIdCreator setId(String id) {
        this.id = id;
        return this;
    }

    @Override
    public MarkTrackingCompletedByIdResponse create(AfterShipClient client) throws Exception {
        if (id == null || id.isEmpty()) {
            throw new ApiException(ErrorEnum.BAD_REQUEST.name(), "Invalid request: `id` is invalid");
        }
        String path = String.format("/tracking/2025-07/trackings/%s/mark-as-completed", id);
        Request request = new Request(HttpMethod.POST, path);
        request.setBody((new Gson()).toJson(markTrackingCompletedByIdRequest));

        setHeaderParams(request);
        Response response = client.request(request);
        AfterShipResponse<Tracking> responseData = new Gson().fromJson(response.getContent(), new TypeToken<AfterShipResponse<Tracking>>() {
            }.getType());
        MarkTrackingCompletedByIdResponse result = new MarkTrackingCompletedByIdResponse();
        result.setData(responseData.getData());
        result.setResponseHeader(response.getResponseHeader());
        return result;
    }

}
