/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.last_checkpoint;

import com.aftership.base.Resource;

public class LastCheckpointResource extends Resource {
    public static GetCheckpointByTrackingIdFetcher getCheckpointByTrackingId() {
        return new GetCheckpointByTrackingIdFetcher();
    }
    public static GetCheckpointBySlugTrackingNumberFetcher getCheckpointBySlugTrackingNumber() {
        return new GetCheckpointBySlugTrackingNumberFetcher();
    }
}
