/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.tracking.model;

import com.aftership.tracking.base.Resource;
import com.google.gson.annotations.SerializedName;

public class CheckpointEvents extends Resource {

  @SerializedName("code")
  private String code;

  @SerializedName("reason")
  private CheckpointEventsReason reason;

  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public CheckpointEventsReason getReason() {
    return reason;
  }

  public void setReason(CheckpointEventsReason reason) {
    this.reason = reason;
  }
}
