/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.tracking.model;

import com.google.gson.annotations.SerializedName;

public enum CheckpointSource {
  @SerializedName("carrier")
  Carrier("carrier"),

  @SerializedName("user")
  User("user");

  private final String value;

  CheckpointSource(final String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }
}
