/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.tracking.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.tracking.base.Resource;

public class CheckpointEventsReason extends Resource {

    @SerializedName("code")
    private String code;

    public  String getCode() {
        return code;
    }

    public void setCode( String code) {
        this.code = code;
    }

}
