/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.tracking.model;

import com.aftership.tracking.base.Resource;
import com.google.gson.annotations.SerializedName;

public class CourierResponse extends Resource {

  @SerializedName("meta")
  private Meta meta;

  @SerializedName("data")
  private CourierResponseData data;

  public Meta getMeta() {
    return meta;
  }

  public void setMeta(Meta meta) {
    this.meta = meta;
  }

  public CourierResponseData getData() {
    return data;
  }

  public void setData(CourierResponseData data) {
    this.data = data;
  }
}
