/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.tracking.model;

import com.google.gson.annotations.SerializedName;

public enum CreateTrackingRequestShipmentDirection {
  @SerializedName("forward")
  Forward("forward"),

  @SerializedName("return")
  Return("return");

  private final String value;

  CreateTrackingRequestShipmentDirection(final String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }
}
