/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.tracking.model;

import com.google.gson.annotations.SerializedName;

public enum CreateTrackingRequestDeliveryType {
  @SerializedName("pickup_at_store")
  PickupAtStore("pickup_at_store"),

  @SerializedName("door_to_door")
  DoorToDoor("door_to_door"),

  @SerializedName("pickup_at_courier")
  PickupAtCourier("pickup_at_courier");

  private final String value;

  CreateTrackingRequestDeliveryType(final String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }
}
