/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.tracking.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.tracking.base.Resource;
import java.util.List;
import java.util.Map;

public class GetCourierConnectionsResponse extends Resource {

    private java.util.Map<String, java.util.List<String>> responseHeader;

    private GetCourierConnectionsResponseData data;

    public java.util.Map<String, java.util.List<String>> getResponseHeader() {
        return responseHeader;
    }

    public void setResponseHeader(java.util.Map<String, java.util.List<String>> responseHeader) {
        this.responseHeader = responseHeader;
    }

    public GetCourierConnectionsResponseData getData() {
        return data;
    }

    public void setData(GetCourierConnectionsResponseData data) {
        this.data = data;
    }
}
