/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.tracking.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.tracking.base.Resource;

public class GetCourierConnectionsResponseData extends Resource {

    @SerializedName("pagination")
    private GetCourierConnectionsResponseDataPagination pagination;

    @SerializedName("courier_connections")
    private java.util.List<CourierConnection> courierConnections;

    public  GetCourierConnectionsResponseDataPagination getPagination() {
        return pagination;
    }

    public void setPagination( GetCourierConnectionsResponseDataPagination pagination) {
        this.pagination = pagination;
    }

    public java.util.List<CourierConnection>  getCourierConnections() {
        return courierConnections;
    }

    public void setCourierConnections(java.util.List<CourierConnection>  courierConnections) {
        this.courierConnections = courierConnections;
    }

}
