/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.tracking.model;

import com.aftership.tracking.base.Resource;

public class GetTrackingsResponse extends Resource {

  private java.util.Map<String, java.util.List<String>> responseHeader;

  private GetTrackingsResponseData data;

  public java.util.Map<String, java.util.List<String>> getResponseHeader() {
    return responseHeader;
  }

  public void setResponseHeader(java.util.Map<String, java.util.List<String>> responseHeader) {
    this.responseHeader = responseHeader;
  }

  public GetTrackingsResponseData getData() {
    return data;
  }

  public void setData(GetTrackingsResponseData data) {
    this.data = data;
  }
}
