/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.tracking.model;

import com.google.gson.annotations.SerializedName;

public enum MarkTrackingCompletedByIdRequestReason {
    @SerializedName("DELIVERED")
    Delivered("DELIVERED"),

    @SerializedName("LOST")
    Lost("LOST"),

    @SerializedName("RETURNED_TO_SENDER")
    ReturnedToSender("RETURNED_TO_SENDER");

    private final String value;

    MarkTrackingCompletedByIdRequestReason(final String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }
}
