/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.tracking.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.tracking.base.Resource;

public class MarkTrackingCompletedByIdRequest extends Resource {

    @SerializedName("reason")
    private MarkTrackingCompletedByIdRequestReason reason;

    @SerializedName("event_datetime")
    private String eventDatetime;

    public  MarkTrackingCompletedByIdRequestReason getReason() {
        return reason;
    }

    public void setReason( MarkTrackingCompletedByIdRequestReason reason) {
        this.reason = reason;
    }

    public  String getEventDatetime() {
        return eventDatetime;
    }

    public void setEventDatetime( String eventDatetime) {
        this.eventDatetime = eventDatetime;
    }

}
