/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.tracking.model;

import com.google.gson.annotations.SerializedName;

public enum MetaType {
    @SerializedName("BadRequest")
    BadRequest("BadRequest"),

    @SerializedName("Unauthorized")
    Unauthorized("Unauthorized"),

    @SerializedName("Forbidden")
    Forbidden("Forbidden"),

    @SerializedName("NotFound")
    NotFound("NotFound"),

    @SerializedName("TooManyRequests")
    TooManyRequests("TooManyRequests"),

    @SerializedName("InternalError")
    InternalError("InternalError");

    private final String value;

    MetaType(final String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }
}
