/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.tracking.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.tracking.base.Resource;

public class PredictBatchResponseData extends Resource {

    @SerializedName("estimated_delivery_dates")
    private java.util.List<EstimatedDeliveryDateResponse> estimatedDeliveryDates;

    public java.util.List<EstimatedDeliveryDateResponse>  getEstimatedDeliveryDates() {
        return estimatedDeliveryDates;
    }

    public void setEstimatedDeliveryDates(java.util.List<EstimatedDeliveryDateResponse>  estimatedDeliveryDates) {
        this.estimatedDeliveryDates = estimatedDeliveryDates;
    }

}
