/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.tracking.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.tracking.base.Resource;

public class PutCourierConnectionsByIdRequest extends Resource {

    @SerializedName("credentials")
    private java.util.Map<String,String> credentials;

    public  java.util.Map<String,String> getCredentials() {
        return credentials;
    }

    public void setCredentials( java.util.Map<String,String> credentials) {
        this.credentials = credentials;
    }

}
