/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.tracking.model;

import com.google.gson.annotations.SerializedName;

public enum SlugGroup {
    @SerializedName("amazon-group")
    AmazonGroup("amazon-group"),

    @SerializedName("fedex-group")
    FedexGroup("fedex-group"),

    @SerializedName("toll-group")
    TollGroup("toll-group"),

    @SerializedName("taqbin-group")
    TaqbinGroup("taqbin-group"),

    @SerializedName("tnt-group")
    TntGroup("tnt-group"),

    @SerializedName("cj-group")
    CjGroup("cj-group"),

    @SerializedName("hermes-group")
    HermesGroup("hermes-group"),

    @SerializedName("dpd-group")
    DpdGroup("dpd-group"),

    @SerializedName("gls-group")
    GlsGroup("gls-group"),

    @SerializedName("dhl-group")
    DhlGroup("dhl-group"),

    @SerializedName("fastway-group")
    FastwayGroup("fastway-group"),

    @SerializedName("asendia-group")
    AsendiaGroup("asendia-group");

    private final String value;

    SlugGroup(final String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }
}
