/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.tracking.model;

import com.google.gson.annotations.SerializedName;

public enum Tag {
  @SerializedName("Pending")
  Pending("Pending"),

  @SerializedName("InfoReceived")
  InfoReceived("InfoReceived"),

  @SerializedName("InTransit")
  InTransit("InTransit"),

  @SerializedName("OutForDelivery")
  OutForDelivery("OutForDelivery"),

  @SerializedName("AttemptFail")
  AttemptFail("AttemptFail"),

  @SerializedName("Delivered")
  Delivered("Delivered"),

  @SerializedName("AvailableForPickup")
  AvailableForPickup("AvailableForPickup"),

  @SerializedName("Exception")
  Exception("Exception"),

  @SerializedName("Expired")
  Expired("Expired");

  private final String value;

  Tag(final String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }
}
