/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.tracking.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.tracking.base.Resource;

public class TrackingFirstEstimatedDelivery extends Resource {

    @SerializedName("type")
    private TrackingFirstEstimatedDeliveryType type;

    @SerializedName("source")
    private TrackingFirstEstimatedDeliverySource source;

    @SerializedName("datetime")
    private String datetime;

    @SerializedName("datetime_min")
    private String datetimeMin;

    @SerializedName("datetime_max")
    private String datetimeMax;

    public  TrackingFirstEstimatedDeliveryType getType() {
        return type;
    }

    public void setType( TrackingFirstEstimatedDeliveryType type) {
        this.type = type;
    }

    public  TrackingFirstEstimatedDeliverySource getSource() {
        return source;
    }

    public void setSource( TrackingFirstEstimatedDeliverySource source) {
        this.source = source;
    }

    public  String getDatetime() {
        return datetime;
    }

    public void setDatetime( String datetime) {
        this.datetime = datetime;
    }

    public  String getDatetimeMin() {
        return datetimeMin;
    }

    public void setDatetimeMin( String datetimeMin) {
        this.datetimeMin = datetimeMin;
    }

    public  String getDatetimeMax() {
        return datetimeMax;
    }

    public void setDatetimeMax( String datetimeMax) {
        this.datetimeMax = datetimeMax;
    }

}
