/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.tracking.model;

import com.aftership.tracking.base.Resource;
import com.google.gson.annotations.SerializedName;

public class TrackingCustomEstimatedDeliveryDate extends Resource {

  @SerializedName("type")
  private TrackingCustomEstimatedDeliveryDateType type;

  @SerializedName("datetime")
  private String datetime;

  @SerializedName("datetime_min")
  private String datetimeMin;

  @SerializedName("datetime_max")
  private String datetimeMax;

  public TrackingCustomEstimatedDeliveryDateType getType() {
    return type;
  }

  public void setType(TrackingCustomEstimatedDeliveryDateType type) {
    this.type = type;
  }

  public String getDatetime() {
    return datetime;
  }

  public void setDatetime(String datetime) {
    this.datetime = datetime;
  }

  public String getDatetimeMin() {
    return datetimeMin;
  }

  public void setDatetimeMin(String datetimeMin) {
    this.datetimeMin = datetimeMin;
  }

  public String getDatetimeMax() {
    return datetimeMax;
  }

  public void setDatetimeMax(String datetimeMax) {
    this.datetimeMax = datetimeMax;
  }
}
