/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.tracking.model;

import com.google.gson.annotations.SerializedName;

public enum TrackingFirstEstimatedDeliverySource {
    @SerializedName("Carrier EDD")
    CarrierEdd("Carrier EDD"),

    @SerializedName("AfterShip EDD")
    AfterShipEdd("AfterShip EDD"),

    @SerializedName("Custom EDD")
    CustomEdd("Custom EDD"),

    @SerializedName("Order EDD")
    OrderEdd("Order EDD");

    private final String value;

    TrackingFirstEstimatedDeliverySource(final String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }
}
