/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.tracking.model;

import com.aftership.tracking.base.Resource;
import com.google.gson.annotations.SerializedName;

public class TrackingMultiPieceInfo extends Resource {

  @SerializedName("type")
  private TrackingMultiPieceInfoType type;

  @SerializedName("pieces")
  private java.util.List<TrackingMultiPieceInfoPieces> pieces;

  public TrackingMultiPieceInfoType getType() {
    return type;
  }

  public void setType(TrackingMultiPieceInfoType type) {
    this.type = type;
  }

  public java.util.List<TrackingMultiPieceInfoPieces> getPieces() {
    return pieces;
  }

  public void setPieces(java.util.List<TrackingMultiPieceInfoPieces> pieces) {
    this.pieces = pieces;
  }
}
