/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.tracking.model;

import com.aftership.tracking.base.Resource;
import com.google.gson.annotations.SerializedName;

public class TrackingLatestEstimatedDelivery extends Resource {

  @SerializedName("type")
  private TrackingLatestEstimatedDeliveryType type;

  @SerializedName("source")
  private TrackingLatestEstimatedDeliverySource source;

  @SerializedName("datetime")
  private String datetime;

  @SerializedName("datetime_min")
  private String datetimeMin;

  @SerializedName("datetime_max")
  private String datetimeMax;

  @SerializedName("revise_reason")
  private String reviseReason;

  public TrackingLatestEstimatedDeliveryType getType() {
    return type;
  }

  public void setType(TrackingLatestEstimatedDeliveryType type) {
    this.type = type;
  }

  public TrackingLatestEstimatedDeliverySource getSource() {
    return source;
  }

  public void setSource(TrackingLatestEstimatedDeliverySource source) {
    this.source = source;
  }

  public String getDatetime() {
    return datetime;
  }

  public void setDatetime(String datetime) {
    this.datetime = datetime;
  }

  public String getDatetimeMin() {
    return datetimeMin;
  }

  public void setDatetimeMin(String datetimeMin) {
    this.datetimeMin = datetimeMin;
  }

  public String getDatetimeMax() {
    return datetimeMax;
  }

  public void setDatetimeMax(String datetimeMax) {
    this.datetimeMax = datetimeMax;
  }

  public String getReviseReason() {
    return reviseReason;
  }

  public void setReviseReason(String reviseReason) {
    this.reviseReason = reviseReason;
  }
}
