/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.tracking.model;

import com.aftership.tracking.base.Resource;
import com.google.gson.annotations.SerializedName;

public class TrackingResponseForGetTrackingsData extends Resource {

  @SerializedName("pagination")
  private TrackingResponseForGetTrackingsDataPagination pagination;

  @SerializedName("trackings")
  private java.util.List<Tracking> trackings;

  public TrackingResponseForGetTrackingsDataPagination getPagination() {
    return pagination;
  }

  public void setPagination(TrackingResponseForGetTrackingsDataPagination pagination) {
    this.pagination = pagination;
  }

  public java.util.List<Tracking> getTrackings() {
    return trackings;
  }

  public void setTrackings(java.util.List<Tracking> trackings) {
    this.trackings = trackings;
  }
}
