/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.tracking.model;

import com.google.gson.annotations.SerializedName;
import com.aftership.tracking.base.Resource;

public class TrackingResponseForGetTrackings extends Resource {

    @SerializedName("meta")
    private Meta meta;

    @SerializedName("data")
    private TrackingResponseForGetTrackingsData data;

    public  Meta getMeta() {
        return meta;
    }

    public void setMeta( Meta meta) {
        this.meta = meta;
    }

    public  TrackingResponseForGetTrackingsData getData() {
        return data;
    }

    public void setData( TrackingResponseForGetTrackingsData data) {
        this.data = data;
    }

}
