/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.tracking.model;

import com.aftership.tracking.base.Resource;
import com.google.gson.annotations.SerializedName;

public class TrackingMultiPieceInfoPieces extends Resource {

  @SerializedName("tracking_id")
  private String trackingId;

  @SerializedName("tracking_number")
  private String trackingNumber;

  @SerializedName("type")
  private TrackingMultiPieceInfoPiecesType type;

  @SerializedName("trackable")
  private Boolean trackable;

  public String getTrackingId() {
    return trackingId;
  }

  public void setTrackingId(String trackingId) {
    this.trackingId = trackingId;
  }

  public String getTrackingNumber() {
    return trackingNumber;
  }

  public void setTrackingNumber(String trackingNumber) {
    this.trackingNumber = trackingNumber;
  }

  public TrackingMultiPieceInfoPiecesType getType() {
    return type;
  }

  public void setType(TrackingMultiPieceInfoPiecesType type) {
    this.type = type;
  }

  public Boolean getTrackable() {
    return trackable;
  }

  public void setTrackable(Boolean trackable) {
    this.trackable = trackable;
  }
}
