/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.tracking.model;

import com.aftership.tracking.base.Resource;
import com.google.gson.annotations.SerializedName;

public class TrackingForwardShipment extends Resource {

  @SerializedName("id")
  private String id;

  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }
}
