/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.tracking.model;

import com.aftership.tracking.base.Resource;
import com.google.gson.annotations.SerializedName;

public class TrackingProofOfDelivery extends Resource {

  @SerializedName("type")
  private String type;

  @SerializedName("url")
  private String url;

  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }
}
