/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.tracking.model;

import com.aftership.tracking.base.Resource;
import com.google.gson.annotations.SerializedName;

public class TrackingResponse extends Resource {

  @SerializedName("meta")
  private Meta meta;

  @SerializedName("data")
  private Tracking data;

  public Meta getMeta() {
    return meta;
  }

  public void setMeta(Meta meta) {
    this.meta = meta;
  }

  public Tracking getData() {
    return data;
  }

  public void setData(Tracking data) {
    this.data = data;
  }
}
