/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.tracking.base;

import com.aftership.tracking.http.AfterShipClient;
import com.aftership.tracking.TrackingSdk;

public abstract class Deleter<T extends Resource> {

    public T delete() throws Exception {
        return delete(TrackingSdk.getRestClient());
    }

    public abstract T delete(final AfterShipClient client) throws Exception;
}
