/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.tracking.base;

import com.aftership.tracking.TrackingSdk;
import com.aftership.tracking.http.AfterShipClient;

public abstract class Fetcher<T extends Resource> {

    public T fetch() throws Exception {
        return fetch(TrackingSdk.getRestClient());
    }

    public abstract T fetch(final AfterShipClient client) throws Exception;
}
