/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.tracking.base;

import com.aftership.tracking.TrackingSdk;
import com.aftership.tracking.http.AfterShipClient;

public abstract class Updater<T extends Resource> {

  public T update() throws Exception {
    return update(TrackingSdk.getRestClient());
  }

  public abstract T update(final AfterShipClient client) throws Exception;
}
