/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.exception;

import java.util.Arrays;
import org.apache.http.Header;

public class ApiException extends Exception {

  private final Integer metaCode;
  private final String message;
  private final Integer code;
  private final Integer statusCode;
  private final String responseBody;
  private final Header[] headers;

  public ApiException(final int code, final String message) {
    this.metaCode = 0;
    this.message = message;
    this.statusCode = 0;
    this.code = code;
    this.responseBody = "";
    this.headers = null;
  }

  public ApiException(
      final int metaCode,
      final String message,
      final int code,
      final int statusCode,
      final String responseBody,
      final Header[] headers) {
    this.metaCode = metaCode;
    this.message = message;
    this.code = code;
    this.statusCode = statusCode;
    this.responseBody = responseBody;
    this.headers = headers;
  }

  public Integer getMetaCode() {
    return metaCode;
  }

  @Override
  public String getMessage() {
    return message;
  }

  public Integer getCode() {
    return code;
  }

  public Integer getStatusCode() {
    return statusCode;
  }

  public String getResponseBody() {
    return responseBody;
  }

  public Header[] getHeaders() {
    return headers;
  }

  @Override
  public String toString() {
    return "ApiException{"
        + "metaCode="
        + metaCode
        + ", message='"
        + message
        + '\''
        + ", code="
        + code
        + ", statusCode="
        + statusCode
        + ", responseBody='"
        + responseBody
        + '\''
        + ", headers="
        + Arrays.toString(headers)
        + '}';
  }
}
