/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.courier;

import com.aftership.base.Resource;

public class CourierResource extends Resource {
    public static DetectCourierCreator detectCourier() {
        return new DetectCourierCreator();
    }

    public static GetAllCouriersFetcher getAllCouriers() {
        return new GetAllCouriersFetcher();
    }

    public static GetUserCouriersFetcher getUserCouriers() {
        return new GetUserCouriersFetcher();
    }
}
