/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.courier;

import com.aftership.base.Fetcher;
import com.aftership.http.*;
import com.aftership.model.GetUserCouriersResponse;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.util.HashMap;
import java.util.Map;

public class GetUserCouriersFetcher extends Fetcher<GetUserCouriersResponse> {
  private final Map<String, String> headerParams = new HashMap<>(8);

  public GetUserCouriersFetcher addHeaderParam(final String name, final String value) {
    if (value == null || value.equals("null")) {
      return this;
    }

    if (!headerParams.containsKey(name)) {
      headerParams.put(name, value);
    }
    return this;
  }

  private void setHeaderParams(final Request request) {
    for (final Map.Entry<String, String> entry : headerParams.entrySet()) {
      request.addHeaderParam(entry.getKey(), entry.getValue());
    }
  }

  @Override
  public GetUserCouriersResponse fetch(AfterShipClient client) throws Exception {
    String path = "/tracking/2025-01/couriers";
    Request request = new Request(HttpMethod.GET, path);
    setHeaderParams(request);
    Response response = client.request(request);
    AfterShipResponse<GetUserCouriersResponse> trackingResponse =
        new Gson()
            .fromJson(
                response.getContent(),
                new TypeToken<AfterShipResponse<GetUserCouriersResponse>>() {}.getType());
    return trackingResponse.getData();
  }
}
