/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.tracking.courier;

import com.aftership.tracking.base.Resource;

public class CourierResource extends Resource {
    public static GetCouriersFetcher getCouriers() {
        return new GetCouriersFetcher();
    }
    public static DetectCourierCreator detectCourier() {
        return new DetectCourierCreator();
    }
}
