/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.tracking.constant;

import java.util.HashMap;
import java.util.Map;

public enum ErrorEnum {
    INVALID_API_KEY,
    INVALID_OPTION,
    BAD_REQUEST,
    RATE_LIMIT_EXCEED,
    TIMED_OUT,
    UNKNOWN_ERROR,
    INVALID_REQUEST,
    INVALID_JSON,
    TRACKING_ALREADY_EXIST,
    TRACKING_DOES_NOT_EXIST,
    TRACKING_NUMBER_INVALID,
    TRACKING_REQUIRED,
    TRACKING_NUMBER_REQUIRED,
    VALUE_INVALID,
    VALUE_REQUIRED,
    SLUG_INVALID,
    MISSING_OR_INVALID_REQUIRED_FIELD,
    BAD_COURIER,
    INACTIVE_RETRACK_NOT_ALLOWED,
    NOTIFICATION_REQUIRED,
    ID_INVALID,
    RETRACK_ONCE_ALLOWED,
    TRACKING_NUMBER_FORMAT_INVALID,
    API_KEY_INVALID,
    REQUEST_NOT_ALLOWED,
    NOT_FOUND,
    TOO_MANY_REQUEST,
    INTERNAL_ERROR;

    private static final Map<Integer, ErrorEnum> META_CODE_MAP = new HashMap<Integer, ErrorEnum>() {
        {
            put(400, INVALID_REQUEST);
            put(4001, INVALID_JSON);
            put(4003, TRACKING_ALREADY_EXIST);
            put(4004, TRACKING_DOES_NOT_EXIST);
            put(4005, TRACKING_NUMBER_INVALID);
            put(4006, TRACKING_REQUIRED);
            put(4007, TRACKING_NUMBER_REQUIRED);
            put(4008, VALUE_INVALID);
            put(4009, VALUE_REQUIRED);
            put(4010, SLUG_INVALID);
            put(4011, MISSING_OR_INVALID_REQUIRED_FIELD);
            put(4012, BAD_COURIER);
            put(4013, INACTIVE_RETRACK_NOT_ALLOWED);
            put(4014, NOTIFICATION_REQUIRED);
            put(4015, ID_INVALID);
            put(4016, RETRACK_ONCE_ALLOWED);
            put(4017, TRACKING_NUMBER_FORMAT_INVALID);
            put(401, API_KEY_INVALID);
            put(403, REQUEST_NOT_ALLOWED);
            put(404, NOT_FOUND);
            put(429, TOO_MANY_REQUEST);
            put(500, INTERNAL_ERROR);
            put(502, INTERNAL_ERROR);
            put(503, INTERNAL_ERROR);
            put(504, INTERNAL_ERROR);
        }
    };

    public static String getCode(int statusCode, int metaCode) {
        ErrorEnum e = META_CODE_MAP.get(metaCode);
        if (e != null) {
            return e.name();
        }

        if (statusCode >= 400 && statusCode < 500) {
            return ErrorEnum.BAD_REQUEST.name();
        }

        return ErrorEnum.UNKNOWN_ERROR.name();
    }
}