/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.notification;

import com.aftership.base.Creator;
import com.aftership.constant.ErrorEnum;
import com.aftership.exception.ApiException;
import com.aftership.http.*;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.util.HashMap;
import java.util.Map;
import com.aftership.http.Request;
import com.aftership.model.DeleteNotificationByTrackingIdResponse;
import com.aftership.base.Page;
import com.aftership.model.DeleteNotificationByTrackingIdRequest;
import com.aftership.model.Notification;
import com.aftership.model.NotificationRequestV1;

import com.aftership.model.DeleteNotificationByTrackingIdResponse;

public class DeleteNotificationByTrackingIdCreator extends Creator<Notification> {
    private final Map<String, String> headerParams= new HashMap<>(8);

    public DeleteNotificationByTrackingIdCreator addHeaderParam(final String name, final String value) {
        if (value == null || value.equals("null")) {
            return this;
        }

        if (!headerParams.containsKey(name)) {
            headerParams.put(name, value);
        }
        return this;
    }

    private void setHeaderParams(final Request request) {
        for (final Map.Entry<String, String> entry : headerParams.entrySet()) {
            request.addHeaderParam(entry.getKey(), entry.getValue());
        }
    }
    private NotificationRequestV1 deleteNotificationByTrackingIdRequest;

    public DeleteNotificationByTrackingIdCreator setNotificationRequestV1(NotificationRequestV1 deleteNotificationByTrackingIdRequest) {
        this.deleteNotificationByTrackingIdRequest = deleteNotificationByTrackingIdRequest;
        return this;
    }
    private String tracking_id;


    public DeleteNotificationByTrackingIdCreator setTrackingId(String tracking_id) {
        this.tracking_id = tracking_id;
        return this;
    }

    @Override
    public Notification create(AfterShipClient client) throws Exception {
        if (tracking_id == null || tracking_id.isEmpty()) {
            throw new ApiException(ErrorEnum.BAD_REQUEST.getCode(), ErrorEnum.BAD_REQUEST.getMessage() + ": `tracking_id` is invalid");
        }
        String path = String.format("/tracking/2024-04/notifications/%s/remove", tracking_id);
        Request request = new Request(HttpMethod.POST, path);
        DeleteNotificationByTrackingIdRequest NotificationRequestV1 = new DeleteNotificationByTrackingIdRequest();
        NotificationRequestV1.setNotification(deleteNotificationByTrackingIdRequest);
        request.setBody((new Gson()).toJson(NotificationRequestV1));

        setHeaderParams(request);
        Response response = client.request(request);
        AfterShipResponse<DeleteNotificationByTrackingIdResponse> trackingResponse = new Gson().fromJson(response.getContent(), new TypeToken<AfterShipResponse<DeleteNotificationByTrackingIdResponse>>() {
            }.getType());
        return trackingResponse.getData().getNotification();

    }

}
