/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
package com.aftership.notification;

import com.aftership.base.Resource;

public class NotificationResource extends Resource {
    public static AddNotificationBySlugTrackingNumberCreator addNotificationBySlugTrackingNumber() {
        return new AddNotificationBySlugTrackingNumberCreator();
    }
    public static GetNotificationByTrackingIdFetcher getNotificationByTrackingId() {
        return new GetNotificationByTrackingIdFetcher();
    }
    public static AddNotificationByTrackingIdCreator addNotificationByTrackingId() {
        return new AddNotificationByTrackingIdCreator();
    }
    public static DeleteNotificationByTrackingIdCreator deleteNotificationByTrackingId() {
        return new DeleteNotificationByTrackingIdCreator();
    }
    public static GetNotificationBySlugTrackingNumberFetcher getNotificationBySlugTrackingNumber() {
        return new GetNotificationBySlugTrackingNumberFetcher();
    }
    public static DeleteNotificationBySlugTrackingNumberCreator deleteNotificationBySlugTrackingNumber() {
        return new DeleteNotificationBySlugTrackingNumberCreator();
    }
}
